### ISSUE TITLE
UML Diagrams not working

### ISSUE THREAD

**Issue by ursjoss** [hackergarten/hackadoc#27]
See HackMD [feature description](https://hackmd.io/features#uml-diagrams). also amend `feature.adoc`

* Sequence Diagrams
* Flow charts
* Mermaid
* Graphviz
* Abc

**Comment by ghost** [comment]
This issue caused by asciidoctor.js. So , we cannot implement this.

**Comment by ghost** [comment]
sry. That information is wrong.asciidoctor.js's extension comes true plantuml and etc...
So, I try to implement that extension.
