### ISSUE TITLE
Table column alignment not working

### ISSUE THREAD

**Issue by ursjoss** [hackergarten/hackadoc#29]
While tables in general do render, aligning columns differently from the default does not (e.g. right align).

See HackMD [feature description](https://hackmd.io/features#tables). also amend `feature.adoc`

**Comment by madmas** [comment]
Yes, tables seem to work fine, the alignment ssems to have some problems.
I too kthe examples from http://mrhaki.blogspot.de/2014/11/awesome-asciidoctor-table-column-and.html and it did not render as expected. 

Next, we should check if it is a known asciidoctor.js issue.
